### PR TITLE
Version update 201501

### PR DESCRIPTION
**Pull request by chrisroat**

### CODE REVIEW

**Comment by deflaux** [comment]
thanks @chrisroat !

**Comment by pgrosu** [comment]
The update looks great Chris, but only one minor thing:

[eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page) now is now at `3.2.4` which has some major fixes since `3.2.1` - below is a link to the changelog detailing this:

http://eigen.tuxfamily.org/index.php?title=ChangeLog#Eigen_3.2.4

~p

**Comment by chrisroat** [comment]
Hi Paul,

Thanks for pointing out that eigen is behind.  I plan another update soon,
with some additional software.  I'll include a version bump for eigen, as
well.

C

**Comment by pgrosu** [comment]
Hi Chris,

That sounds great!  It was no biggie - just a helpful comment :)

Thanks,
~p

**Pull request merged**
